apiVersion: apps/v1
kind: Deployment
metadata:
  name: inspiring-quotes-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inspiring-quotes-api
  template:
    metadata:
      labels:
        app: inspiring-quotes-api
    spec:
      containers:
        - name: inspiring-quotes-api
          image: itsjeevesh/inspiring-quotes-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
