apiVersion: v1
kind: Service
metadata:
  name: inspiring-quotes-api
spec:
  type: NodePort
  selector:
    app: inspiring-quotes-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007 